//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        public int ID_ARTICULO { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_COMPRA { get; set; }
        public decimal PRECIO_VENTA1 { get; set; }
        public decimal PRECIO_VENTA2 { get; set; }
        public decimal PRECIO_VENTA3 { get; set; }
        public int STOCK_MININO { get; set; }
        public string ESTADO { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREADO { get; set; }
        public byte[] IMAGEN { get; set; }
    }
}
