//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public string REFERENCIA { get; set; }
        public string NOMBRE { get; set; }
        public int ID_TIPO_IDENTIFICACION { get; set; }
        public string NUMERO_IDENTIFICACION { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public string ESTADO { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_CREADO { get; set; }
        public string DIRECCION_TRABAJO { get; set; }
        public string NOMBRE_CONYUGUE { get; set; }
        public string TELEFONO_CONYUGUE { get; set; }
        public string CASA_PROPIA { get; set; }
        public string NOMBRE_REFERENCIA1 { get; set; }
        public string DIRECCION_REFERENCIA1 { get; set; }
        public string TELEFONO_REFERENCIA1 { get; set; }
        public string OBSERVACION_REFERENCIA1 { get; set; }
        public string NOMBRE_REFERENCIA2 { get; set; }
        public string DIRECCION_REFERENCIA2 { get; set; }
        public string TELEFONO_REFERENCIA2 { get; set; }
        public string OBSERVACION_REFERENCIA2 { get; set; }
        public string OBSERVACION { get; set; }
    }
}
