//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRADORES
    {
        public int ID_COBRADOR { get; set; }
        public string NOMBRE { get; set; }
        public int ID_TIPO_IDENTIFICACION { get; set; }
        public string NUMERO_IDENTIFICACION { get; set; }
        public string ESTADO { get; set; }
        public string SEXO { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREADO { get; set; }
        public string RUTA { get; set; }
    }
}
