//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUADRES_DIARIOS
    {
        public string FECHA { get; set; }
        public decimal VALOR_PAGADO { get; set; }
        public decimal VALOR_ANULADO { get; set; }
        public decimal VALOR_CXP_PAGADO { get; set; }
        public decimal VALOR_CXP_ANULADO { get; set; }
        public decimal VALOR_TOTAL { get; set; }
    }
}
