//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXP
    {
        public int ID_CXP { get; set; }
        public int ID_MOVIMIENTO { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public decimal MONTO_TOTAL { get; set; }
        public decimal MONTO_PAGADO { get; set; }
        public decimal MONTO_PENDIENTE { get; set; }
        public string ESTADO { get; set; }
        public string OBSERVACION { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREADO { get; set; }
        public string ANULADO_POR { get; set; }
        public string FECHA_ANULACION { get; set; }
        public string NOTA_ANULACION { get; set; }
    }
}
