//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES_CUOTAS
    {
        public int ID_FACTURA { get; set; }
        public int NUMERO_CUOTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO_CUOTA { get; set; }
        public decimal MONTO_PAGADO { get; set; }
        public decimal MONTO_PENDIENTE { get; set; }
    }
}
