//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIVOS_MOVIMIENTOS
    {
        public int ID_MOTIVO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public string OBSERVACION { get; set; }
    }
}
