//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS
    {
        public int ID_MOVIMIENTO { get; set; }
        public int ID_MOTIVO { get; set; }
        public int ID_ARTICULO { get; set; }
        public int CANTIDAD { get; set; }
        public string ESTADO { get; set; }
        public string OBSERVACION { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREADO { get; set; }
        public string ANULADO_POR { get; set; }
        public string FECHA_ANULADO { get; set; }
        public string NOTA_ANULACION { get; set; }
    }
}
