//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS_CXP
    {
        public int ID_PAGO { get; set; }
        public int ID_CXP { get; set; }
        public decimal MONTO_PAGADO { get; set; }
        public string ESTADO { get; set; }
        public string OBSERVACION { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREADO { get; set; }
        public string ANULADO_POR { get; set; }
        public string FECHA_ANULACION { get; set; }
        public string NOTA_ANULACION { get; set; }
        public string FORMA_PAGO { get; set; }
    }
}
