//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORES
    {
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public int ID_TIPO_IDENTIFICACION { get; set; }
        public string NUMERO_IDENTIFICACION { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREADO { get; set; }
    }
}
