//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_IDENTIFICACIONES
    {
        public int ID_TIPO_IDENTIFICACION { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
